EXPERIMENT:
  NAME: ""
  TAG: "KD-RL,res56,res20"
  PROJECT: "RL-KD"
DISTILLER:
  TYPE: "KD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
KD:
  RL_STATE_TOP_K: 30
  DELAY_EPOCHS_RATIO: 0.2
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"